### ISSUE TITLE
Refine Input Field

### ISSUE THREAD

**Issue by BradleyLi** [Anidion/flatmates#7]
Improve the behavior and appearance of the input field component to enhance user experience.

#### Tasks
- [x] **Set Text Color**: Adjust the `TextField` to display typed text in black, as it is currently appearing in white.
- [x] **Add Secure Field Option**: Implement a secure input type to hide text for password fields. Currently, everything is in clear text.
- [x] **Make the text typed in the fields stay persistent**: Once switching from the one input filed to the other, the text type before disappeared.
